// zenweb service typing
// This file is automatically generated
// Please do not modify
// directory: /Users/yefei/develop/zenweb/zenweb-blank/src/service
// date: 2021/12/24 下午4:25:48
// user: yefei@-
import DemoService from '../service/demo_service';
import User from '../service/user';

declare module '@zenweb/service' {
  interface Services {
    demoService: DemoService;
    user: User;
  }
}
