// zenweb service typing
// This file is automatically generated
// Please do not modify
// date: 2021/12/23 下午4:30:13
// user: yefei@unknown

// directory: /Users/yefei/develop/zenweb/zenweb-blank/src/service
import DemoService from '../service/demo_service';
import User from '../service/user';

declare module '@zenweb/service' {
  interface Services {
    demoService: DemoService;
    user: User;
  }
}
