// zenweb service typing
// This file is automatically generated
// Please do not modify
import DemoService from './demo_service';
import User from './user';

declare module '@zenweb/service' {
  interface Services {
    demoService: DemoService;
    user: User;
  }
}
