// zenorm auto generate
// This file is automatically generated
// Please do not modify
// date: 2021/12/13 下午1:24:36
// user: yefei@unknown
// database: test
import { Instance, Model, Query } from 'zenorm';

/**
 * table: message
 */
export declare class MessageInstance extends Instance {
  /**
   * int(11) auto_increment
   */
  id: number;
  /**
   * int(11) 
   */
  user_id: number;
  /**
   * varchar(255) 
   */
  content: string;
}

export declare class MessageModel extends Model<MessageInstance> {}
export declare function MessageQuery(query: Query): MessageModel;

/**
 * table: nonautopk
 */
export declare class NonautopkInstance extends Instance {
  /**
   * int(11) 
   */
  id: number;
  /**
   * varchar(255) 
   */
  name: string;
}

export declare class NonautopkModel extends Model<NonautopkInstance> {}
export declare function NonautopkQuery(query: Query): NonautopkModel;

/**
 * table: profile
 */
export declare class ProfileInstance extends Instance {
  /**
   * int(11) auto_increment
   */
  id: number;
  /**
   * int(11) 
   */
  user_id: number;
  /**
   * varchar(255) 
   */
  edu: string;
  /**
   * varchar(255) 
   */
  work: string;
}

export declare class ProfileModel extends Model<ProfileInstance> {}
export declare function ProfileQuery(query: Query): ProfileModel;

/**
 * table: user
 */
export declare class UserInstance extends Instance {
  /**
   * int(11) auto_increment
   */
  id: number;
  /**
   * varchar(255) 
   */
  name: string;
  /**
   * date 
   */
  birthday: string;
  /**
   * datetime 
   */
  created_at: Date;
  /**
   * datetime on update CURRENT_TIMESTAMP
   */
  updated_at: Date;
}

export declare class UserModel extends Model<UserInstance> {}
export declare function UserQuery(query: Query): UserModel;

export declare class Queries {
  constructor(query: Query);
  message: MessageModel;
  nonautopk: NonautopkModel;
  profile: ProfileModel;
  user: UserModel;
}

export declare function queries(query: Query): Queries;

declare module 'koa' {
  interface BaseContext {
    model: Queries;
  }
}
